<?php

declare(strict_types=1);

namespace Golem\Cli\Server;

use Golem\Cli\Filesystem;
use Golem\Cli\Project;
use Golem\Cli\UserError;

/**
 * A throwaway server folder: a fresh flat world, the Golem runtime, and a link to
 * the plugin under test. Every run starts from a clean slate.
 */
final class Workspace
{
    private function __construct(
        public readonly string $path,
        public readonly int $port,
    ) {
    }

    /**
     * @param array{seed: int, seconds: int, golems: int}|null $fuzz
     * @param array{steps: list<int>, seconds: int}|null $bench
     * @param list<string>|null $testFiles only run the tests of these files
     * @param array{repeat: int, seed: ?int, perTestCoverage?: bool, stopOnFailure?: bool}|null $order how many times, and in which order, to run the tests
     */
    public static function create(Project $project, string $golemSource, ?string $filter, string $cacheDirectory, bool $updateSnapshots = false, bool $coverage = false, ?array $fuzz = null, ?array $bench = null, ?array $testFiles = null, ?array $order = null): self
    {
        $path = sys_get_temp_dir() . '/golem-' . bin2hex(random_bytes(6));
        foreach (['', '/plugins', '/subjects'] as $directory) {
            if (!mkdir($path . $directory, 0777, true) && !is_dir($path . $directory)) {
                throw new UserError("Cannot create the server folder $path$directory");
            }
        }

        $workspace = new self($path, self::freePort());
        $workspace->writeServerProperties();
        $workspace->writeBootstrapPlugin($golemSource);
        $workspace->linkPlugins($project);
        $workspace->writeRuntimeConfig($project, $filter, $cacheDirectory, $updateSnapshots, $coverage, $fuzz, $bench, $testFiles, $order);

        return $workspace;
    }

    public function eventsFile(): string
    {
        return $this->path . '/events.jsonl';
    }

    public function runtimeConfig(): string
    {
        return $this->path . '/golem.json';
    }

    public function logFile(): string
    {
        return $this->path . '/console.log';
    }

    public function delete(): void
    {
        Filesystem::remove($this->path);
    }

    private function writeServerProperties(): void
    {
        $properties = [
            'motd' => 'Golem test server',
            'server-ip' => '127.0.0.1',
            'server-port' => $this->port,
            'enable-ipv6' => 'off',
            'enable-query' => 'off',
            'xbox-auth' => 'off',
            'white-list' => 'off',
            'max-players' => 200,
            'level-name' => 'golem',
            'level-type' => 'flat',
            'level-seed' => 'golem',
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'view-distance' => 4,
            'auto-save' => 'off',
            'language' => 'eng',
        ];

        $lines = ['# Generated by Golem for a test run'];
        foreach ($properties as $key => $value) {
            $lines[] = "$key=$value";
        }
        file_put_contents($this->path . '/server.properties', implode("\n", $lines) . "\n");
    }

    /**
     * A one-file script plugin: PocketMine reads the docblock as plugin.yml, and the
     * code below it makes the Golem classes autoloadable from their real location.
     */
    private function writeBootstrapPlugin(string $golemSource): void
    {
        $source = var_export($golemSource, true);
        $script = <<<PHP
            <?php

            /**
             * @name GolemTestRunner
             * @main Golem\\Runtime\\GolemPlugin
             * @version 1.0.0
             * @api 5.0.0
             * @load STARTUP
             */

            declare(strict_types=1);

            \\pocketmine\\Server::getInstance()->getLoader()->addPath('Golem\\\\', $source);

            PHP;
        file_put_contents($this->path . '/plugins/golem.php', $script);
    }

    private function linkPlugins(Project $project): void
    {
        self::link($project->root, $this->path . '/subjects/' . self::safeName($project->name));

        foreach ($project->extraPlugins as $plugin) {
            // phars load from plugins/ with PocketMine's own loader, source folders with Golem's
            $target = str_ends_with($plugin, '.phar') ? '/plugins/' : '/subjects/';
            self::link($plugin, $this->path . $target . basename($plugin));
        }
    }

    /**
     * @param array{seed: int, seconds: int, golems: int}|null $fuzz
     * @param array{steps: list<int>, seconds: int}|null $bench
     * @param list<string>|null $testFiles
     * @param array{repeat: int, seed: ?int, perTestCoverage?: bool, stopOnFailure?: bool}|null $order
     */
    private function writeRuntimeConfig(Project $project, ?string $filter, string $cacheDirectory, bool $updateSnapshots, bool $coverage, ?array $fuzz, ?array $bench, ?array $testFiles, ?array $order): void
    {
        file_put_contents($this->runtimeConfig(), json_encode([
            'events' => $this->eventsFile(),
            'tests' => $project->testsDirectory,
            'subjects' => $this->path . '/subjects',
            'subject' => $project->name,
            'filter' => $filter,
            'files' => $testFiles,
            'repeat' => $order['repeat'] ?? 1,
            'seed' => $order['seed'] ?? null,
            'perTestCoverage' => $order['perTestCoverage'] ?? false,
            'stopOnFailure' => $order['stopOnFailure'] ?? false,
            'pluginRoot' => $project->root,
            'cache' => $cacheDirectory,
            'virions' => $project->virions,
            'poggit' => $project->poggitManifest,
            'updateSnapshots' => $updateSnapshots,
            'coverage' => $coverage,
            'fuzz' => $fuzz,
            'bench' => $bench,
            'ci' => getenv('CI') !== false && getenv('CI') !== '' && getenv('CI') !== 'false',
        ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
        touch($this->eventsFile());
    }

    private static function link(string $target, string $link): void
    {
        if (!@symlink($target, $link)) {
            throw new UserError("Cannot link $target into the test server.");
        }
    }

    private static function safeName(string $name): string
    {
        return (string) preg_replace('/[^A-Za-z0-9_.-]/', '_', $name);
    }

    /**
     * Asks the OS for a free UDP port, so several runs can happen side by side.
     */
    private static function freePort(): int
    {
        $socket = @stream_socket_server('udp://127.0.0.1:0', $errno, $error, STREAM_SERVER_BIND);
        if ($socket === false) {
            return random_int(30000, 60000);
        }
        $name = (string) stream_socket_get_name($socket, false);
        fclose($socket);
        $port = (int) substr($name, (int) strrpos($name, ':') + 1);

        return $port > 0 ? $port : random_int(30000, 60000);
    }
}
